
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/packet-radio/ultimatepr/internal/tncproxy"


)

var tests = []testing.InternalTest{

	{"TestProxySharesUpstreamWithMultipleClients", _test.TestProxySharesUpstreamWithMultipleClients},

	{"TestProxyBlocksCommandsThatCanTakeOverSharedTNC", _test.TestProxyBlocksCommandsThatCanTakeOverSharedTNC},

	{"TestAddressAllowedByHostname", _test.TestAddressAllowedByHostname},

	{"TestAddressAllowedByIPv6WildcardWithZone", _test.TestAddressAllowedByIPv6WildcardWithZone},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ImportPath = "github.com/packet-radio/ultimatepr/internal/tncproxy"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

