
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/packet-radio/ultimatepr/internal/web"


)

var tests = []testing.InternalTest{

	{"TestPasswordHash", _test.TestPasswordHash},

	{"TestLoginDetailsCanChangeUsernameWithoutChangingPassword", _test.TestLoginDetailsCanChangeUsernameWithoutChangingPassword},

	{"TestAllowAddressesAcceptsZonedIPv6Remote", _test.TestAllowAddressesAcceptsZonedIPv6Remote},

	{"TestPersistentSessionToken", _test.TestPersistentSessionToken},

	{"TestAddressAllowed", _test.TestAddressAllowed},

	{"TestConfigRestartRequired", _test.TestConfigRestartRequired},

	{"TestBeaconEndpointAlwaysSendsClassicBeacon", _test.TestBeaconEndpointAlwaysSendsClassicBeacon},

	{"TestMHeardDirectExcludesUPRDReports", _test.TestMHeardDirectExcludesUPRDReports},

	{"TestValidateWebListenerRejectsUnavailableAddress", _test.TestValidateWebListenerRejectsUnavailableAddress},

	{"TestValidateWebListenerAcceptsAvailableAddress", _test.TestValidateWebListenerAcceptsAvailableAddress},

	{"TestTerminalMessageFromEventUsesDataForPayload", _test.TestTerminalMessageFromEventUsesDataForPayload},

	{"TestTerminalMessageFromEventFallsBackToMessage", _test.TestTerminalMessageFromEventFallsBackToMessage},

	{"TestTerminalTemplateExpansion", _test.TestTerminalTemplateExpansion},

	{"TestAutomaticWelcomePayloadEndsWithCRLF", _test.TestAutomaticWelcomePayloadEndsWithCRLF},

	{"TestExpandTerminalMessageAtSendTime", _test.TestExpandTerminalMessageAtSendTime},

	{"TestPrepareTerminalMessagePreservesUTF8", _test.TestPrepareTerminalMessagePreservesUTF8},

	{"TestMonitorClearEndpoint", _test.TestMonitorClearEndpoint},

	{"TestTerminalRemoteCommandsRequireSlashAndSeparateLine", _test.TestTerminalRemoteCommandsRequireSlashAndSeparateLine},

	{"TestTerminalHelpListsRemoteCommands", _test.TestTerminalHelpListsRemoteCommands},

	{"TestTerminalVersionResponse", _test.TestTerminalVersionResponse},

	{"TestInboundViaFormatsReturnPath", _test.TestInboundViaFormatsReturnPath},

	{"TestHasActiveBrowserTracksNotificationConnections", _test.TestHasActiveBrowserTracksNotificationConnections},

	{"TestBrowserKickChannelClosesPreviousConnection", _test.TestBrowserKickChannelClosesPreviousConnection},

	{"TestOperatorStationRunsInBackgroundWithoutBrowser", _test.TestOperatorStationRunsInBackgroundWithoutBrowser},

	{"TestBranchReleaseEndpoint", _test.TestBranchReleaseEndpoint},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ImportPath = "github.com/packet-radio/ultimatepr/internal/web"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

