
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/packet-radio/ultimatepr/internal/config"


)

var tests = []testing.InternalTest{

	{"TestWebDefaultsAndPasswordHashIsPrivate", _test.TestWebDefaultsAndPasswordHashIsPrivate},

	{"TestWebAllowedAddressesAcceptHostname", _test.TestWebAllowedAddressesAcceptHostname},

	{"TestPortProxyJSONFieldsRoundTrip", _test.TestPortProxyJSONFieldsRoundTrip},

	{"TestExampleConfiguration", _test.TestExampleConfiguration},

	{"TestTerminalMessageDefaults", _test.TestTerminalMessageDefaults},

	{"TestTerminalAX25Defaults", _test.TestTerminalAX25Defaults},

	{"TestRejectsInvalidTerminalAX25Settings", _test.TestRejectsInvalidTerminalAX25Settings},

	{"TestLegacyWelcomeGetsCommandHintWithoutOverwritingCustomWelcome", _test.TestLegacyWelcomeGetsCommandHintWithoutOverwritingCustomWelcome},

	{"TestBeaconViaConfiguration", _test.TestBeaconViaConfiguration},

	{"TestPortEnabledDefaultsAndDisable", _test.TestPortEnabledDefaultsAndDisable},

	{"TestRejectsKISSPortAbove15", _test.TestRejectsKISSPortAbove15},

	{"TestAcceptsTNCProxy", _test.TestAcceptsTNCProxy},

	{"TestTNCProxyDefaultsToPort8101", _test.TestTNCProxyDefaultsToPort8101},

	{"TestSaveRejectsInvalidWithoutChangingFile", _test.TestSaveRejectsInvalidWithoutChangingFile},

	{"TestSaveModelRoundTrip", _test.TestSaveModelRoundTrip},

	{"TestCleanFirstRunModes", _test.TestCleanFirstRunModes},

	{"TestInvalidLocatorRejected", _test.TestInvalidLocatorRejected},

	{"TestValidLocatorAccepted", _test.TestValidLocatorAccepted},

	{"TestUPRDDefaultsOnLegacyConfigButHonorsExplicitDisable", _test.TestUPRDDefaultsOnLegacyConfigButHonorsExplicitDisable},

	{"TestStableChannelMigratesToMain", _test.TestStableChannelMigratesToMain},

	{"TestLegacyServicesBecomeExperimental", _test.TestLegacyServicesBecomeExperimental},

	{"TestExplicitExperimentalDisableIsPreserved", _test.TestExplicitExperimentalDisableIsPreserved},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ImportPath = "github.com/packet-radio/ultimatepr/internal/config"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

