
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/packet-radio/ultimatepr/internal/mheard"


)

var tests = []testing.InternalTest{

	{"TestPlannedRestartSnapshotPreservesFreshConfiguredPorts", _test.TestPlannedRestartSnapshotPreservesFreshConfiguredPorts},

	{"TestBeaconKeepsFrameCountAndUpdatesText", _test.TestBeaconKeepsFrameCountAndUpdatesText},

	{"TestDirectEntryReplacesIndirectReport", _test.TestDirectEntryReplacesIndirectReport},

	{"TestBeaconExpiresAndUpdates", _test.TestBeaconExpiresAndUpdates},

	{"TestOldEntryDisappearsFromList", _test.TestOldEntryDisappearsFromList},

	{"TestDirectPortChoosesNewestDirectObservation", _test.TestDirectPortChoosesNewestDirectObservation},

	{"TestHeardViaKeepsReversePathWithoutReplacingDirectRoute", _test.TestHeardViaKeepsReversePathWithoutReplacingDirectRoute},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ImportPath = "github.com/packet-radio/ultimatepr/internal/mheard"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

