
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/packet-radio/ultimatepr/internal/session"


)

var tests = []testing.InternalTest{

	{"TestInboundAX25Service", _test.TestInboundAX25Service},

	{"TestInboundIgnoresUnknownDestination", _test.TestInboundIgnoresUnknownDestination},

	{"TestInboundDisconnectedServiceRespondsDM", _test.TestInboundDisconnectedServiceRespondsDM},

	{"TestInboundDisconnectedDMAlwaysSetsFinal", _test.TestInboundDisconnectedDMAlwaysSetsFinal},

	{"TestInboundAnswersSupervisoryPoll", _test.TestInboundAnswersSupervisoryPoll},

	{"TestInboundAnswersXIDWithoutStartingService", _test.TestInboundAnswersXIDWithoutStartingService},

	{"TestInboundEchoesTESTCommand", _test.TestInboundEchoesTESTCommand},

	{"TestInboundServiceUsesDISCHandshakeOnClose", _test.TestInboundServiceUsesDISCHandshakeOnClose},

	{"TestInboundRoutedServiceReceivesReturnPath", _test.TestInboundRoutedServiceReceivesReturnPath},

	{"TestConnectSendReceiveDisconnect", _test.TestConnectSendReceiveDisconnect},

	{"TestConnectNegotiatesXIDResponseParameters", _test.TestConnectNegotiatesXIDResponseParameters},

	{"TestSendWithProgressReportsEveryPaclenFrame", _test.TestSendWithProgressReportsEveryPaclenFrame},

	{"TestSendSplitsAtSpacesAndPreservesOriginalText", _test.TestSendSplitsAtSpacesAndPreservesOriginalText},

	{"TestPayloadWithoutWhitespaceUsesHardPaclenLimit", _test.TestPayloadWithoutWhitespaceUsesHardPaclenLimit},

	{"TestSendIgnoresStaleAcknowledgementWithoutImmediateRetry", _test.TestSendIgnoresStaleAcknowledgementWithoutImmediateRetry},

	{"TestSendRetriesImmediatelyOnRejectForCurrentSequence", _test.TestSendRetriesImmediatelyOnRejectForCurrentSequence},

	{"TestSendRetriesImmediatelyOnSelectiveReject", _test.TestSendRetriesImmediatelyOnSelectiveReject},

	{"TestConnectTimeout", _test.TestConnectTimeout},

	{"TestConnectRejectsUAWithoutFinalBit", _test.TestConnectRejectsUAWithoutFinalBit},

	{"TestConnectRejectsInvalidCommandResponseBits", _test.TestConnectRejectsInvalidCommandResponseBits},

	{"TestUAWithFinalThenImmediateLinBPQBannerIsDelivered", _test.TestUAWithFinalThenImmediateLinBPQBannerIsDelivered},

	{"TestProtocolDefaults", _test.TestProtocolDefaults},

	{"TestConnectRequiresTargetCallsign", _test.TestConnectRequiresTargetCallsign},

	{"TestConnectIncludesDigipeaterPath", _test.TestConnectIncludesDigipeaterPath},

	{"TestKeepAliveUsesSupervisoryFrame", _test.TestKeepAliveUsesSupervisoryFrame},

	{"TestOutOfSequenceIFrameSendsSingleREJ", _test.TestOutOfSequenceIFrameSendsSingleREJ},

	{"TestRNRPausesNextIFrameUntilRR", _test.TestRNRPausesNextIFrameUntilRR},

	{"TestRNRDoesNotRetransmitUnacknowledgedIWhileBusy", _test.TestRNRDoesNotRetransmitUnacknowledgedIWhileBusy},

	{"TestT1ExpiryPollsBeforeRetransmittingIFrame", _test.TestT1ExpiryPollsBeforeRetransmittingIFrame},

	{"TestRemoteDISCUAMirrorsPollBit", _test.TestRemoteDISCUAMirrorsPollBit},

	{"TestT1N2ExhaustionDisconnectsLostLink", _test.TestT1N2ExhaustionDisconnectsLostLink},

	{"TestKeepAliveDisconnectsUnresponsiveStation", _test.TestKeepAliveDisconnectsUnresponsiveStation},

	{"TestConnectedDMImmediatelyDropsLink", _test.TestConnectedDMImmediatelyDropsLink},

	{"TestRemoteDMInterruptsOutstandingSend", _test.TestRemoteDMInterruptsOutstandingSend},

	{"TestRemoteDMDuringTimerRecoveryDoesNotReconnect", _test.TestRemoteDMDuringTimerRecoveryDoesNotReconnect},

	{"TestSimultaneousSABMCompletesConnection", _test.TestSimultaneousSABMCompletesConnection},

	{"TestRepeatedSABMResetsConnectedLink", _test.TestRepeatedSABMResetsConnectedLink},

	{"TestDelayedDuplicateUAAfterRetriedSABMDoesNotDropLink", _test.TestDelayedDuplicateUAAfterRetriedSABMDoesNotDropLink},

	{"TestHubClaimsOutgoingInformationBeforeInboundMux", _test.TestHubClaimsOutgoingInformationBeforeInboundMux},

	{"TestXIDUsesIndependentManagementRetryLimit", _test.TestXIDUsesIndependentManagementRetryLimit},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ImportPath = "github.com/packet-radio/ultimatepr/internal/session"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

