
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/packet-radio/ultimatepr/internal/terminalcodec"


)

var tests = []testing.InternalTest{

	{"TestUTF8RoundTrip", _test.TestUTF8RoundTrip},

	{"TestUTF8PreservesSplitRuneAcrossPackets", _test.TestUTF8PreservesSplitRuneAcrossPackets},

	{"TestSupportedListsOnlyUTF8", _test.TestSupportedListsOnlyUTF8},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ImportPath = "github.com/packet-radio/ultimatepr/internal/terminalcodec"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

