package language

import "strings"

func Normalize(v string) string {
	if strings.EqualFold(strings.TrimSpace(v), "en") {
		return "en"
	}
	return "pl"
}
func T(lang, key string) string {
	if Normalize(lang) == "en" {
		if v, ok := en[key]; ok {
			return v
		}
	}
	if v, ok := pl[key]; ok {
		return v
	}
	return key
}

var polishASCII = strings.NewReplacer("ą", "a", "ć", "c", "ę", "e", "ł", "l", "ń", "n", "ó", "o", "ś", "s", "ź", "z", "ż", "z", "Ą", "A", "Ć", "C", "Ę", "E", "Ł", "L", "Ń", "N", "Ó", "O", "Ś", "S", "Ź", "Z", "Ż", "Z")

func ASCII(v string) string { return polishASCII.Replace(v) }

var pl = map[string]string{
	"game_welcome": "\r\nSALON GIER\r\n", "game_lobby": "1 Gry\r\n2 Gracze\r\n3 Zaproszenia\r\n4 Pomoc\r\n5 Wyjscie\r\n", "game_games": "TIC-TAC-TOE - PLAY <znak>\r\n", "game_players_header": "GRACZE\r\n", "game_status_lobby": "Lobby", "game_status_waiting": "Oczekuje", "game_status_playing": "Gra", "game_no_invites": "Brak zaproszen.\r\n", "game_help": "PLAY <znak> | PLAYERS | INVITES | ACCEPT <id> | DECLINE <id> | QUIT\r\n", "game_play_usage": "Uzycie: PLAY <znak>\r\n", "game_accept_usage": "Uzycie: ACCEPT <id>\r\n", "game_decline_usage": "Uzycie: DECLINE <id>\r\n", "game_unknown": "Nieznane polecenie. Wpisz HELP.\r\n", "game_goodbye": "73!\r\n", "game_connect_error": "Nie mozna wejsc do Salonu Gier.\r\n", "game_invited": "%s zaprasza Cie do TIC-TAC-TOE [%s]. ACCEPT %s lub DECLINE %s.\r\n", "game_invite_sent": "Zaproszenie %s wyslane do %s.\r\n", "game_invite_expired": "Zaproszenie %s wygaslo.\r\n", "game_declined": "Zaproszenie %s odrzucone.\r\n", "game_started": "Gra %s rozpoczeta. X zaczyna.\r\n", "game_turn": "Ruch: %s\r\n", "game_draw": "Remis.\r\n", "game_winner": "Wygrywa %s.\r\n", "game_finished_help": "REMATCH - rewanz | QUIT - lobby\r\n", "game_rematch_request": "%s proponuje rewanz. Wpisz REMATCH, aby zaakceptowac.\r\n", "game_rematch_started": "Rewanz rozpoczety.\r\n", "game_back_lobby": "Powrot do lobby.\r\n", "game_left": "%s opuscil gre.\r\n", "game_disconnected": "%s rozlaczyl sie. Gra przerwana.\r\n", "game_invalid": "Nieprawidlowa akcja.\r\n", "game_not_turn": "To nie Twoj ruch.\r\n", "game_occupied": "Pole jest zajete.\r\n", "game_already_finished": "Gra jest zakonczona.\r\n", "ttt_help": "TIC-TAC-TOE\r\nCel: uloz 3 znaki w jednej linii.\r\nRuch: wpisz wspolrzedne, np. B2.\r\nBOARD - pokaz plansze\r\nHELP - pomoc\r\nQUIT - wyjdz\r\n",
	"callsign": "Znak: ", "invalid_call": "Nieprawidlowy znak.\r\n", "db_error": "Blad bazy danych.\r\n", "hello_bbs": "Witaj %s. Wpisz H, aby zobaczyc pomoc.\r\n",
	"bbs_help":    "H pomoc | L lista | I informacje | LM lista | LN/N nowe | LS wyslane | LB biuletyny | R <id> czytaj | RE <id> odpowiedz | S/SP <znak@BBS> prywatna | SB <obszar> biuletyn | ST <znak@BBS> NTS | FS <id> forwarding | K <id> usun | PROFILE | NAME | HOMEBBS | QTH | LOC | CONV | LANG PL/EN | B powrot\r\n",
	"no_messages": "Brak wiadomosci.\r\n", "no_new": "Brak nowych wiadomosci.\r\n", "usage_read": "Uzycie: R <id>\r\n", "invalid_id": "Nieprawidlowy numer.\r\n", "error": "Blad: %v\r\n", "usage_kill": "Uzycie: K <id>\r\n", "deleted": "Usunieto.\r\n", "usage_send": "Uzycie: S <znak lub znak@BBS>\r\n", "unknown": "Nieznane polecenie. Wpisz H.\r\n", "subject": "Temat: ", "body": "Wpisz tresc. Zakoncz linia /EX.\r\n", "saved": "Wiadomosc #%d zostala zapisana.\r\n", "return_node": "Powrot do noda.\r\n", "lang_set": "Jezyk ustawiony na polski.\r\n", "lang_usage": "Uzycie: LANG PL albo LANG EN\r\n", "reply_subject": "Odp: %s", "forward_none": "Wiadomosc nie jest w kolejce forwardingu.\r\n", "forward_line": "%-12s stan=%-9s proby=%d blad=%s\r\n", "usage_reply": "Uzycie: RE <id>\r\n", "usage_forward": "Uzycie: FS <id>\r\n",
	"node_call": "Znak: ", "hello_node": "Witaj %s. Wpisz ?, aby zobaczyc pomoc.\r\n", "node_help": "NODES | ROUTES | PORTS | SERVICES | BBS | C <usluga/znak> | LANG PL/EN | BYE\r\n", "no_neighbors": "Brak aktywnych sasiadow.\r\n", "no_routes": "Brak aktywnych tras.\r\n", "bbs_unavailable": "BBS jest niedostepny.\r\n", "usage_connect": "Uzycie: C <usluga/znak>\r\n", "no_route": "Brak trasy do %s.\r\n", "route_found": "Trasa %s przez %s, port %s, jakosc %d. Rzeczywiste lacze bedzie dodane w kolejnym etapie.\r\n", "returned": "Powrot do noda.\r\n", "lang_pl": "Jezyk ustawiony na polski.\r\n", "lang_en": "Language changed to English.\r\n",
}
var en = map[string]string{
	"game_welcome": "\r\nGAME HALL\r\n", "game_lobby": "1 Games\r\n2 Players\r\n3 Invitations\r\n4 Help\r\n5 Exit\r\n", "game_games": "TIC-TAC-TOE - PLAY <callsign>\r\n", "game_players_header": "PLAYERS\r\n", "game_status_lobby": "Lobby", "game_status_waiting": "Waiting", "game_status_playing": "Playing", "game_no_invites": "No invitations.\r\n", "game_help": "PLAY <callsign> | PLAYERS | INVITES | ACCEPT <id> | DECLINE <id> | QUIT\r\n", "game_play_usage": "Usage: PLAY <callsign>\r\n", "game_accept_usage": "Usage: ACCEPT <id>\r\n", "game_decline_usage": "Usage: DECLINE <id>\r\n", "game_unknown": "Unknown command. Type HELP.\r\n", "game_goodbye": "73!\r\n", "game_connect_error": "Cannot enter the Game Hall.\r\n", "game_invited": "%s invites you to TIC-TAC-TOE [%s]. ACCEPT %s or DECLINE %s.\r\n", "game_invite_sent": "Invitation %s sent to %s.\r\n", "game_invite_expired": "Invitation %s expired.\r\n", "game_declined": "Invitation %s declined.\r\n", "game_started": "Game %s started. X moves first.\r\n", "game_turn": "Turn: %s\r\n", "game_draw": "Draw.\r\n", "game_winner": "%s wins.\r\n", "game_finished_help": "REMATCH - play again | QUIT - lobby\r\n", "game_rematch_request": "%s requests a rematch. Type REMATCH to accept.\r\n", "game_rematch_started": "Rematch started.\r\n", "game_back_lobby": "Back to lobby.\r\n", "game_left": "%s left the game.\r\n", "game_disconnected": "%s disconnected. Game interrupted.\r\n", "game_invalid": "Invalid action.\r\n", "game_not_turn": "It is not your turn.\r\n", "game_occupied": "Field is occupied.\r\n", "game_already_finished": "Game is finished.\r\n", "ttt_help": "TIC-TAC-TOE\r\nGoal: make a line of 3 marks.\r\nMove: enter coordinates, for example B2.\r\nBOARD - show board\r\nHELP - help\r\nQUIT - leave\r\n",
	"callsign": "Callsign: ", "invalid_call": "Invalid callsign.\r\n", "db_error": "Database error.\r\n", "hello_bbs": "Hello %s. Type H for help.\r\n", "bbs_help": "H help | L list | I information | LM list | LN/N new | LS sent | LB bulletins | R <id> read | RE <id> reply | S/SP <call@BBS> private | SB <area> bulletin | ST <call@BBS> NTS | FS <id> forwarding | K <id> delete | PROFILE | NAME | HOMEBBS | QTH | LOC | CONV | LANG PL/EN | B return\r\n", "no_messages": "No messages.\r\n", "no_new": "No new messages.\r\n", "usage_read": "Usage: R <id>\r\n", "invalid_id": "Invalid message number.\r\n", "error": "Error: %v\r\n", "usage_kill": "Usage: K <id>\r\n", "deleted": "Deleted.\r\n", "usage_send": "Usage: SP <call or call@BBS>\r\n", "unknown": "Unknown command. Type H.\r\n", "subject": "Subject: ", "body": "Enter text. Finish with /EX on a separate line.\r\n", "saved": "Message #%d saved.\r\n", "return_node": "Return to node.\r\n", "lang_set": "Language changed to English.\r\n", "lang_usage": "Usage: LANG PL or LANG EN\r\n", "reply_subject": "Re: %s", "forward_none": "Message is not queued for forwarding.\r\n", "forward_line": "%-12s status=%-9s attempts=%d error=%s\r\n", "usage_reply": "Usage: RE <id>\r\n", "usage_forward": "Usage: FS <id>\r\n",
	"node_call": "Callsign: ", "hello_node": "Hello %s. Type ? for help.\r\n", "node_help": "NODES | ROUTES | PORTS | SERVICES | BBS | C <service/call> | LANG PL/EN | BYE\r\n", "no_neighbors": "No active neighbors.\r\n", "no_routes": "No active routes.\r\n", "bbs_unavailable": "BBS unavailable.\r\n", "usage_connect": "Usage: C <service/callsign>\r\n", "no_route": "No route to %s.\r\n", "route_found": "Route %s via %s on %s, quality %d. Live link connection is the next protocol stage.\r\n", "returned": "Returned to node.\r\n", "lang_pl": "Jezyk ustawiony na polski.\r\n", "lang_en": "Language changed to English.\r\n",
}
