
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/packet-radio/ultimatepr/cmd/server"


)

var tests = []testing.InternalTest{

	{"TestBeaconText", _test.TestBeaconText},

	{"TestBeaconTextOmitsMissingOptionalFields", _test.TestBeaconTextOmitsMissingOptionalFields},

	{"TestParseUltimatePRBeaconAndExcludeOwnCalls", _test.TestParseUltimatePRBeaconAndExcludeOwnCalls},

	{"TestDigipeaterOutputPortsUsesMHeardAndDiscoversUnknown", _test.TestDigipeaterOutputPortsUsesMHeardAndDiscoversUnknown},

	{"TestDirectlyHeardRejectsRepeatedPath", _test.TestDirectlyHeardRejectsRepeatedPath},

	{"TestMHeardReturnPathReversesRepeatedDigipeaters", _test.TestMHeardReturnPathReversesRepeatedDigipeaters},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "github.com/packet-radio/ultimatepr"
	testdeps.ImportPath = "github.com/packet-radio/ultimatepr/cmd/server"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

