
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/packet-radio/ultimatepr/internal/ai"


)

var tests = []testing.InternalTest{

	{"TestSessionsKeepSeparateHistory", _test.TestSessionsKeepSeparateHistory},

	{"TestProviderTimeout", _test.TestProviderTimeout},

	{"TestConnectionError", _test.TestConnectionError},

	{"TestResponseLimitAndMarkdown", _test.TestResponseLimitAndMarkdown},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ImportPath = "github.com/packet-radio/ultimatepr/internal/ai"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

