
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/packet-radio/ultimatepr/internal/transport/axudp"


)

var tests = []testing.InternalTest{

	{"TestFCSRoundTrip", _test.TestFCSRoundTrip},

	{"TestAllowList", _test.TestAllowList},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ImportPath = "github.com/packet-radio/ultimatepr/internal/transport/axudp"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

