
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/packet-radio/ultimatepr/internal/transport/kiss"


)

var tests = []testing.InternalTest{

	{"TestEncodeDecodeEscaping", _test.TestEncodeDecodeEscaping},

	{"TestSplitAndMultipleFrames", _test.TestSplitAndMultipleFrames},

	{"TestInvalidEscapeAndOversize", _test.TestInvalidEscapeAndOversize},

	{"TestDecoderDiscardsGarbageBeforeOpeningFEND", _test.TestDecoderDiscardsGarbageBeforeOpeningFEND},

	{"TestDecoderKeepsEscapeStateAcrossReads", _test.TestDecoderKeepsEscapeStateAcrossReads},

	{"TestAcceptFrame", _test.TestAcceptFrame},

	{"TestWriteParameters", _test.TestWriteParameters},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

	{"FuzzDecoder", _test.FuzzDecoder},

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ImportPath = "github.com/packet-radio/ultimatepr/internal/transport/kiss"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

