
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/packet-radio/ultimatepr/internal/uprd"


)

var tests = []testing.InternalTest{

	{"TestPayloadRoundTripAndBaseCall", _test.TestPayloadRoundTripAndBaseCall},

	{"TestPayloadValidation", _test.TestPayloadValidation},

	{"TestStatusIsBinaryAndBitZeroIsParsed", _test.TestStatusIsBinaryAndBitZeroIsParsed},

	{"TestEncodingWrapsAlphabet", _test.TestEncodingWrapsAlphabet},

	{"TestReporterReplacementPreservesOrder", _test.TestReporterReplacementPreservesOrder},

	{"TestOlderReportCannotOverwriteNewer", _test.TestOlderReportCannotOverwriteNewer},

	{"TestParseFrameRejectsViaAndWrongDestination", _test.TestParseFrameRejectsViaAndWrongDestination},

	{"TestBuildFrameUsesBinaryStatusAndKeepsAX25Contract", _test.TestBuildFrameUsesBinaryStatusAndKeepsAX25Contract},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ImportPath = "github.com/packet-radio/ultimatepr/internal/uprd"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

