
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/packet-radio/ultimatepr/internal/bbs"


)

var tests = []testing.InternalTest{

	{"TestTwoBBSForwardingAndASCII", _test.TestTwoBBSForwardingAndASCII},

	{"TestPlanForwardingByAddressAndScope", _test.TestPlanForwardingByAddressAndScope},

	{"TestPrepareAndRecordForwardQueue", _test.TestPrepareAndRecordForwardQueue},

	{"TestTerminalConversation", _test.TestTerminalConversation},

	{"TestSessionLanguageSwitch", _test.TestSessionLanguageSwitch},

	{"TestNewReadReplyAndSentCommands", _test.TestNewReadReplyAndSentCommands},

	{"TestProfilePersistsAndHomeBBSChanges", _test.TestProfilePersistsAndHomeBBSChanges},

	{"TestProfileOptionalFieldsAcceptSkip", _test.TestProfileOptionalFieldsAcceptSkip},

	{"TestHomeBBSExpandsRecipient", _test.TestHomeBBSExpandsRecipient},

	{"TestStorePersistsMail", _test.TestStorePersistsMail},

	{"TestBulletinVisibleToEveryone", _test.TestBulletinVisibleToEveryone},

	{"TestUserLanguagePersists", _test.TestUserLanguagePersists},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ImportPath = "github.com/packet-radio/ultimatepr/internal/bbs"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

