
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/packet-radio/ultimatepr/internal/history"


)

var tests = []testing.InternalTest{

	{"TestOnlyConnectedConversationReceivesLines", _test.TestOnlyConnectedConversationReceivesLines},

	{"TestLegacyHistoryRestoresLineEndings", _test.TestLegacyHistoryRestoresLineEndings},

	{"TestUnversionedRawHistoryDoesNotSplitPacketFragments", _test.TestUnversionedRawHistoryDoesNotSplitPacketFragments},

	{"TestHistoryPreservesPacketBoundariesAndBlankLines", _test.TestHistoryPreservesPacketBoundariesAndBlankLines},

	{"TestHistoryStoresConnectionLifecycle", _test.TestHistoryStoresConnectionLifecycle},

	{"TestHistoryGroupsCallsignAcrossRadioPorts", _test.TestHistoryGroupsCallsignAcrossRadioPorts},

	{"TestDeleteAndClearHistory", _test.TestDeleteAndClearHistory},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ImportPath = "github.com/packet-radio/ultimatepr/internal/history"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

