
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/packet-radio/ultimatepr/internal/netallow"


)

var tests = []testing.InternalTest{

	{"TestAllowed", _test.TestAllowed},

	{"TestValidRule", _test.TestValidRule},

	{"TestParseZonedIPv6", _test.TestParseZonedIPv6},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ImportPath = "github.com/packet-radio/ultimatepr/internal/netallow"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

