
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/packet-radio/ultimatepr/internal/monitor"


)

var tests = []testing.InternalTest{

	{"TestFormatVia", _test.TestFormatVia},

	{"TestAddStoresVia", _test.TestAddStoresVia},

	{"TestTypeNamesRemainStableWhenAX25TypesAreExtended", _test.TestTypeNamesRemainStableWhenAX25TypesAreExtended},

	{"TestClearRemovesBufferedEntriesAndAllowsNewFrames", _test.TestClearRemovesBufferedEntriesAndAllowsNewFrames},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ImportPath = "github.com/packet-radio/ultimatepr/internal/monitor"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

