
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/packet-radio/ultimatepr/internal/ax25"


)

var tests = []testing.InternalTest{

	{"TestAddressRoundTrip", _test.TestAddressRoundTrip},

	{"TestParseDigipeaters", _test.TestParseDigipeaters},

	{"TestFrameTypesRoundTrip", _test.TestFrameTypesRoundTrip},

	{"TestEncodeRejectsInformationOnControlFrame", _test.TestEncodeRejectsInformationOnControlFrame},

	{"TestModulo128NumberedFramesRoundTrip", _test.TestModulo128NumberedFramesRoundTrip},

	{"TestXIDRoundTripAndValidation", _test.TestXIDRoundTripAndValidation},

	{"TestXIDNegotiationUsesTAPRSelectionRules", _test.TestXIDNegotiationUsesTAPRSelectionRules},

	{"TestDecodeRejectsShort", _test.TestDecodeRejectsShort},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

	{"FuzzDecode", _test.FuzzDecode},

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ImportPath = "github.com/packet-radio/ultimatepr/internal/ax25"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

