
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/packet-radio/ultimatepr/internal/digipeater"


)

var tests = []testing.InternalTest{

	{"TestRepeatsFirstPendingMatchingAlias", _test.TestRepeatsFirstPendingMatchingAlias},

	{"TestRejectsWrongNextAliasDuplicateAndOwnFrame", _test.TestRejectsWrongNextAliasDuplicateAndOwnFrame},

	{"TestConnectedModeRetriesAreNotSuppressed", _test.TestConnectedModeRetriesAreNotSuppressed},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ImportPath = "github.com/packet-radio/ultimatepr/internal/digipeater"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

